import { lazy } from "react";

export const LandingPage = lazy(() => import("@/features/landing").then((m) => ({ default: m.LandingPage })));
export const LoginPage = lazy(() => import("@/features/auth").then((m) => ({ default: m.LoginPage })));
export const DashboardPage = lazy(() => import("@/features/dashboard").then((m) => ({ default: m.DashboardPage })));
export const WorkspacePage = lazy(() => import("@/features/workspace").then((m) => ({ default: m.WorkspacePage })));
export const InboxPage = lazy(() => import("@/features/approvals").then((m) => ({ default: m.InboxPage })));
export const ApprovalDetailPage = lazy(() => import("@/features/approvals").then((m) => ({ default: m.ApprovalDetailPage })));
export const RunsPage = lazy(() => import("@/features/runs").then((m) => ({ default: m.RunsPage })));
export const RunDetailPage = lazy(() => import("@/features/runs").then((m) => ({ default: m.RunDetailPage })));
export const RegistryPage = lazy(() => import("@/features/registry").then((m) => ({ default: m.RegistryPage })));
export const DesignDocsPage = lazy(() => import("@/features/design-docs").then((m) => ({ default: m.DesignDocsPage })));
export const QaPage = lazy(() => import("@/features/design-docs").then((m) => ({ default: m.QaPage })));
export const JiraPage = lazy(() => import("@/features/jira").then((m) => ({ default: m.JiraPage })));
export const ProfilePage = lazy(() => import("@/features/profile").then((m) => ({ default: m.ProfilePage })));
export const AuditPage = lazy(() => import("@/features/audit").then((m) => ({ default: m.AuditPage })));
export const UsersPage = lazy(() => import("@/features/admin").then((m) => ({ default: m.UsersPage })));
export const ProjectsPage = lazy(() => import("@/features/admin").then((m) => ({ default: m.ProjectsPage })));
export const AiUsagePage = lazy(() => import("@/features/admin").then((m) => ({ default: m.AiUsagePage })));
export const SettingsPage = lazy(() => import("@/features/admin").then((m) => ({ default: m.SettingsPage })));
export const DeviceApprovalPage = lazy(() => import("@/features/device").then((m) => ({ default: m.DeviceApprovalPage })));
