export const paths = {
  landing: "/",
  login: "/login",
  dashboard: "/app",
  workspace: "/app/workspace",
  workspaceThread: (threadId: string) => `/app/workspace/${threadId}`,
  approvals: "/app/approvals",
  approval: (id: string) => `/app/approvals/${id}`,
  runs: "/app/runs",
  run: (id: string) => `/app/runs/${id}`,
  registry: "/app/agents",
  devFiles: "/app/dev-files",
  devFilesEpic: (epicKey: string) => `/app/dev-files?epic=${encodeURIComponent(epicKey)}`,
  qaFiles: "/app/qa-files",
  jira: "/app/jira",
  profile: "/app/profile",
  audit: "/app/audit",
  users: "/app/admin/users",
} as const;
